spring:
  application:
    name: zuul        #起个名字
    
server:
  port: 3001
  #启动eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
zuul:
  retryable: true
  #重试设置
  
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
#配置路径       可以不配   默认就是

  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
